"""FN-aware selective correction for rumor detection.

This script ranks the samples predicted as non-rumor by the current Transformer
main model, then applies a selective correction policy.

It supports two modes:
1) oracle simulation: flip only the reviewed candidates whose true label is rumor;
2) LLM review: call the configured DeepSeek-based reranker for the top candidates.

The oracle mode is useful for estimating the upper bound of the current
selective-correction strategy on an existing validation set.
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


OBJECTIVE_REPORT_PATTERNS = [
    "video:",
    "watch:",
    "raw video",
    "key moments",
    "statement from",
    "issued a statement",
    "prime minister says",
    "police confirm",
    "police say",
    "official says",
    "calling for calm",
    "has accounted for",
    "last position",
    "was travelling from",
    "when it crashed",
    "crowd gathers",
    "stands by the front entrance",
    "turns the lights off",
]


def is_objective_report_text(text: str) -> bool:
    lowered = text.lower()
    return any(pattern in lowered for pattern in OBJECTIVE_REPORT_PATTERNS)

try:
    from .hybrid_classifier import HybridRumourDetectClass
    from .llm_reranker import LLMReranker
    from .retriever import SimilarExampleRetriever
except ImportError:
    from hybrid_classifier import HybridRumourDetectClass
    from llm_reranker import LLMReranker
    from retriever import SimilarExampleRetriever


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="FN-aware selective correction for rumor detection.")
    parser.add_argument(
        "--predictions",
        default="outputs/final_fusion_with_transformer/predictions.jsonl",
        help="Base prediction jsonl file with true_label/base_label and auxiliary scores.",
    )
    parser.add_argument(
        "--out-dir",
        default="outputs/fn_aware_selective_correction",
        help="Directory for the corrected outputs.",
    )
    parser.add_argument("--top-k", type=int, default=15, help="How many suspicious non-rumor samples to review.")
    parser.add_argument("--review-threshold", type=float, default=0.55, help="Risk score threshold for review.")
    parser.add_argument("--use-llm", action="store_true", help="Use the DeepSeek reranker for reviewed samples.")
    parser.add_argument(
        "--simulate-oracle",
        action="store_true",
        help="Use true labels for reviewed samples to estimate the upper bound of selective correction.",
    )
    parser.add_argument("--model", default="models/ensemble.joblib", help="Local ensemble model path for LLM review.")
    parser.add_argument("--retriever", default="models/retriever.joblib", help="Retriever artifact for LLM review.")
    parser.add_argument("--config", default="config.json", help="Configuration file for the LLM client.")
    parser.add_argument("--top-k-examples", type=int, default=5, help="Number of retrieved examples for the LLM.")
    parser.add_argument("--llm-confidence-min", type=float, default=0.80, help="Minimum LLM confidence required to flip 0 to 1.")
    parser.add_argument(
        "--allowed-evidence-types",
        default="unverified_claim,conspiracy_accusation,sensational_claim",
        help="Comma-separated evidence types that may flip a base non-rumor prediction.",
    )
    parser.add_argument("--min-top1-similarity", type=float, default=0.35, help="Minimum top-1 similarity for rumor-exception flips.")
    parser.add_argument("--min-knn5-rumor-ratio", type=float, default=0.60, help="Minimum top-5 rumor ratio for rumor-exception flips.")
    parser.add_argument("--strict-objective-protection", action="store_true", help="Block flips for obvious objective-report texts.")
    parser.add_argument("--llm-sleep-seconds", type=float, default=7.0, help="Sleep interval between LLM calls to avoid rate limits.")
    parser.add_argument(
        "--audit-features",
        default="outputs/fn_audit_search/all_features.jsonl",
        help="Optional richer feature jsonl generated by audit_fn_and_search_rules.py.",
    )
    return parser.parse_args()


def load_rows(path: str | Path) -> List[Dict[str, Any]]:
    rows = [json.loads(line) for line in Path(path).read_text(encoding="utf-8").splitlines() if line.strip()]
    if not rows:
        raise ValueError(f"No prediction rows found in {path}")
    return rows


def merge_optional_audit_features(rows: List[Dict[str, Any]], audit_path: str | Path) -> List[Dict[str, Any]]:
    path = Path(audit_path)
    if not path.exists():
        return rows
    audit_rows = load_rows(path)
    by_index = {int(r["index"]): r for r in audit_rows if "index" in r}
    merged: List[Dict[str, Any]] = []
    for row in rows:
        audit = by_index.get(int(row["index"]), {})
        new_row = dict(audit)
        new_row.update(row)
        for key in ["knn_rumor_ratio_top3", "knn_rumor_ratio_top7", "retrieved_examples", "event", "id"]:
            if key in audit and key not in row:
                new_row[key] = audit[key]
        merged.append(new_row)
    return merged


def compute_risk_score(row: Dict[str, Any]) -> tuple[float, List[str]]:
    """Score how suspicious a base non-rumor prediction is.

    Higher is more suspicious. This score is only used for selecting a small
    review queue, not for blindly flipping labels.
    """
    score = 0.0
    evidence: List[str] = []

    transformer_prob_1 = float(row.get("transformer_prob_1", 0.0))
    dedicated_prob_1 = float(row.get("dedicated_prob_1", row.get("base_prob_1", 0.0)))
    knn5 = float(row.get("knn_rumor_ratio_top5", 0.0))
    knn3 = float(row.get("knn_rumor_ratio_top3", knn5))
    knn7 = float(row.get("knn_rumor_ratio_top7", knn5))
    top1_label = int(row.get("top1_label", 0))
    top1_similarity = float(row.get("top1_similarity", 0.0))
    base_prob_1 = float(row.get("base_prob_1", 0.0))
    retrieved = row.get("retrieved_examples", []) or []
    retrieved_labels = [int(ex.get("label", 0)) for ex in retrieved[:7] if isinstance(ex, dict)]
    retrieved_top3_ratio = sum(retrieved_labels[:3]) / max(1, len(retrieved_labels[:3])) if retrieved_labels else knn3

    # BERTweet voter is very conservative in this run, so it is a weak signal.
    if transformer_prob_1 >= 0.45:
        score += 0.8
        evidence.append(f"transformer_prob_1={transformer_prob_1:.2f}")
    elif transformer_prob_1 >= 0.20:
        score += 0.3
        evidence.append(f"transformer_prob_1={transformer_prob_1:.2f}")

    if dedicated_prob_1 >= 0.55:
        score += 0.9
        evidence.append(f"dedicated_prob_1={dedicated_prob_1:.2f}")
    elif dedicated_prob_1 >= 0.42:
        score += 0.65
        evidence.append(f"dedicated_prob_1={dedicated_prob_1:.2f}")
    elif dedicated_prob_1 >= 0.25:
        score += 0.25
        evidence.append(f"dedicated_prob_1={dedicated_prob_1:.2f}")

    if knn3 >= 1.0:
        score += 1.0
        evidence.append(f"knn_rumor_ratio_top3={knn3:.2f}")
    elif knn3 >= 0.67:
        score += 0.65
        evidence.append(f"knn_rumor_ratio_top3={knn3:.2f}")

    if knn5 >= 0.80:
        score += 0.55
        evidence.append(f"knn_rumor_ratio_top5={knn5:.2f}")
    elif knn5 >= 0.60:
        score += 0.35
        evidence.append(f"knn_rumor_ratio_top5={knn5:.2f}")

    if knn7 >= 0.57:
        score += 0.35
        evidence.append(f"knn_rumor_ratio_top7={knn7:.2f}")

    if retrieved_top3_ratio >= 1.0:
        score += 0.6
        evidence.append(f"retrieved_top3_rumor_ratio={retrieved_top3_ratio:.2f}")
    elif retrieved_top3_ratio >= 0.67:
        score += 0.35
        evidence.append(f"retrieved_top3_rumor_ratio={retrieved_top3_ratio:.2f}")

    if top1_label == 1 and top1_similarity >= 0.55:
        score += 1.0
        evidence.append(f"top1_label=1,similarity={top1_similarity:.2f}")
    elif top1_label == 1 and top1_similarity >= 0.35:
        score += 0.75
        evidence.append(f"top1_label=1,similarity={top1_similarity:.2f}")
    elif top1_label == 1 and top1_similarity >= 0.20:
        score += 0.35
        evidence.append(f"top1_label=1,similarity={top1_similarity:.2f}")

    if base_prob_1 >= 0.50:
        score += 0.35
        evidence.append(f"base_prob_1={base_prob_1:.2f}")
    elif base_prob_1 >= 0.40:
        score += 0.2
        evidence.append(f"base_prob_1={base_prob_1:.2f}")

    # Penalize cases that are only generic breaking-news reports with a very
    # strong non-rumor nearest neighbour; such cases caused many false flips.
    if top1_label == 0 and top1_similarity >= 0.35:
        score -= 0.35
        evidence.append(f"non_rumor_top1_penalty={top1_similarity:.2f}")

    return score, evidence


def review_with_llm(
    text: str,
    local_label: int,
    local_confidence: float,
    feature_cues: List[str],
    similar_examples: List[Dict[str, Any]],
    reranker: LLMReranker,
) -> Dict[str, Any]:
    return reranker.review(text, local_label, local_confidence, feature_cues, similar_examples)


def make_local_reviewer(model_path: str | Path, retriever_path: str | Path, config_path: str | Path):
    local = HybridRumourDetectClass(model_path=model_path, retriever_path=retriever_path, config_path=config_path, use_llm=False)
    retriever = SimilarExampleRetriever(retriever_path)
    reranker = LLMReranker(config_path=config_path)
    return local, retriever, reranker


def llm_flip_allowed(
    row: Dict[str, Any],
    review_label: Optional[int],
    review_confidence: Optional[float],
    review_evidence_type: Optional[str],
    review_should_flip: Optional[bool],
    args: argparse.Namespace,
) -> tuple[bool, str]:
    if review_label != 1 or not review_should_flip:
        return False, "llm_declined"
    if review_confidence is None or review_confidence < args.llm_confidence_min:
        return False, "low_confidence"
    if review_evidence_type not in {item.strip() for item in args.allowed_evidence_types.split(",") if item.strip()}:
        return False, "disallowed_evidence_type"

    text = str(row.get("text", ""))
    top1_label = int(row.get("top1_label", 0))
    top1_similarity = float(row.get("top1_similarity", 0.0))
    knn5 = float(row.get("knn_rumor_ratio_top5", 0.0))
    objective = is_objective_report_text(text)

    if args.strict_objective_protection and objective:
        return False, "objective_report_protected"

    if top1_label == 1 and top1_similarity >= args.min_top1_similarity and knn5 >= args.min_knn5_rumor_ratio:
        return True, "high_similarity_rumor_exception"

    if review_evidence_type in {"conspiracy_accusation", "unverified_claim"} and top1_label == 1 and top1_similarity >= args.min_top1_similarity:
        return True, "strong_rumor_semantics"

    return False, "insufficient_support"


def main() -> None:
    args = parse_args()
    rows = merge_optional_audit_features(load_rows(args.predictions), args.audit_features)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    candidates: List[Dict[str, Any]] = []
    y_true = [int(r["true_label"]) for r in rows]
    base_pred = [int(r["base_label"]) for r in rows]
    for row in rows:
        if int(row.get("base_label", 0)) != 0:
            continue
        risk_score, evidence = compute_risk_score(row)
        candidate = dict(row)
        candidate["risk_score"] = float(risk_score)
        candidate["risk_evidence"] = evidence
        candidates.append(candidate)

    candidates.sort(key=lambda r: (float(r["risk_score"]), float(r.get("knn_rumor_ratio_top5", 0.0))), reverse=True)

    reviewed = [c for c in candidates if float(c["risk_score"]) >= args.review_threshold][: args.top_k]

    final_rows: List[Dict[str, Any]] = []
    allowed_evidence_types = {
        item.strip()
        for item in str(args.allowed_evidence_types).split(",")
        if item.strip()
    }
    llm_state: Optional[Dict[str, Any]] = None
    if args.use_llm:
        local, retriever, reranker = make_local_reviewer(args.model, args.retriever, args.config)
        llm_state = {
            "model": args.model,
            "retriever": args.retriever,
            "config": args.config,
            "top_k_examples": args.top_k_examples,
            "llm_confidence_min": args.llm_confidence_min,
            "allowed_evidence_types": sorted(allowed_evidence_types),
            "min_top1_similarity": args.min_top1_similarity,
            "min_knn5_rumor_ratio": args.min_knn5_rumor_ratio,
            "strict_objective_protection": args.strict_objective_protection,
            "llm_sleep_seconds": args.llm_sleep_seconds,
        }
    llm_calls = 0
    for row in rows:
        pred = int(row["base_label"])
        corrected = False
        review_label = None
        review_confidence = None
        review_evidence_type = None
        review_should_flip = None
        review_reason = None
        review_source = None
        flip_gate_reason = None
        objective_report_protected = False
        risk_score = None
        evidence: List[str] = []

        if pred == 0:
            match = next((c for c in reviewed if int(c["index"]) == int(row["index"])), None)
            if match is not None:
                risk_score = float(match["risk_score"])
                evidence = list(match["risk_evidence"])
                if args.simulate_oracle:
                    review_label = int(row["true_label"])
                    review_confidence = 1.0
                    review_evidence_type = "oracle"
                    review_should_flip = review_label == 1
                    review_reason = "oracle simulation: reviewed candidates use ground-truth label"
                    review_source = "oracle"
                    if review_label == 1:
                        pred = 1
                        corrected = True
                elif args.use_llm and llm_state is not None:
                    local_label = int(row["base_label"])
                    local_confidence = float(row.get("base_prob_1", 0.0)) if local_label == 1 else 1.0 - float(row.get("base_prob_1", 0.0))
                    if local_confidence <= 0:
                        local_confidence = 0.5
                    feature_cues = evidence[:6]
                    similar_examples = []
                    if retriever is not None:
                        similar_examples = retriever.retrieve(str(row["text"]), k=args.top_k_examples)
                    if llm_calls > 0 and args.llm_sleep_seconds > 0:
                        time.sleep(args.llm_sleep_seconds)
                    llm_review = review_with_llm(
                        str(row["text"]),
                        local_label,
                        local_confidence,
                        feature_cues,
                        similar_examples,
                        reranker,
                    )
                    llm_calls += 1
                    review_label = int(llm_review["label"])
                    review_confidence = float(llm_review.get("confidence", 0.0))
                    review_evidence_type = str(llm_review.get("evidence_type", "unclear"))
                    review_should_flip = bool(llm_review.get("should_flip", False))
                    review_reason = str(llm_review["reason"])
                    review_source = str(llm_review.get("raw", "llm"))
                    objective_report_protected = is_objective_report_text(str(row.get("text", "")))
                    allowed, flip_gate_reason = llm_flip_allowed(
                        row,
                        review_label,
                        review_confidence,
                        review_evidence_type,
                        review_should_flip,
                        args,
                    )
                    if allowed:
                        pred = 1
                        corrected = True

        final_row = dict(row)
        final_row.update(
            {
                "final_label": pred,
                "corrected": corrected,
                "review_label": review_label,
                "review_confidence": review_confidence,
                "review_evidence_type": review_evidence_type,
                "review_should_flip": review_should_flip,
                "review_reason": review_reason,
                "review_source": review_source,
                "flip_gate_reason": flip_gate_reason,
                "objective_report_protected": objective_report_protected,
                "risk_score": risk_score,
                "risk_evidence": evidence,
            }
        )
        final_rows.append(final_row)

    y_pred = [int(r["final_label"]) for r in final_rows]
    acc = accuracy_score(y_true, y_pred)
    report = classification_report(y_true, y_pred, digits=4, output_dict=True)
    cm = confusion_matrix(y_true, y_pred).tolist()

    corrected_count = sum(1 for r in final_rows if bool(r.get("corrected")))
    reviewed_count = len(reviewed)
    recovered_fn = sum(1 for r in final_rows if bool(r.get("corrected")) and int(r["true_label"]) == 1)
    introduced_fp = sum(1 for r in final_rows if bool(r.get("corrected")) and int(r["true_label"]) == 0)

    metrics = {
        "mode": "oracle_simulation" if args.simulate_oracle else ("llm_review" if args.use_llm else "risk_only"),
        "rows": len(final_rows),
        "reviewed_count": reviewed_count,
        "corrected_count": corrected_count,
        "recovered_fn": recovered_fn,
        "introduced_fp": introduced_fp,
        "accuracy": float(acc),
        "classification_report": report,
        "confusion_matrix": cm,
        "selected_review_threshold": float(args.review_threshold),
        "top_k": int(args.top_k),
        "llm_state": llm_state,
    }

    (out_dir / "metrics.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")
    (out_dir / "predictions.jsonl").write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in final_rows),
        encoding="utf-8",
    )
    (out_dir / "candidate_ranking.jsonl").write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in candidates),
        encoding="utf-8",
    )
    (out_dir / "reviewed_candidates.jsonl").write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in reviewed),
        encoding="utf-8",
    )
    (out_dir / "classification_report.txt").write_text(classification_report(y_true, y_pred, digits=4), encoding="utf-8")

    print(json.dumps(metrics, ensure_ascii=False, indent=2))
    print(f"Saved selective-correction outputs to {out_dir}")


if __name__ == "__main__":
    main()
