"""Hybrid rumor detector: local ensemble + retrieval + optional DeepSeek review.

This version is compatible with both:
1) the retained AIrumer ``models/ensemble.joblib`` artifact, and
2) the new ``models/dedicated_local.joblib`` artifact generated by
   ``src/train_dedicated_local.py``.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List

import joblib
import numpy as np

try:
    from .config_utils import load_config
    from .llm_reranker import LLMReranker
    from .retriever import SimilarExampleRetriever
    from .text_utils import preprocess_text
    # Imported so joblib can resolve the class when loading dedicated_local.joblib.
    from .dedicated_model import WeightedProbabilityEnsemble  # noqa: F401
except ImportError:  # pragma: no cover - supports running as ``python src/predict.py``
    from config_utils import load_config
    from llm_reranker import LLMReranker
    from retriever import SimilarExampleRetriever
    from text_utils import preprocess_text
    from dedicated_model import WeightedProbabilityEnsemble  # noqa: F401


LABEL_NAMES = {0: "非谣言", 1: "谣言"}


class EnsembleRumourDetectClass:
    """Local weighted ensemble with model-internal explanations.

    The original AIrumer model stores separate sub-models under ``models`` and
    ``weights``.  The added training script stores a single
    ``WeightedProbabilityEnsemble`` under ``model``.  This class normalizes both
    formats behind the same predict/explain interface.
    """

    def __init__(self, model_path: str | Path = "models/ensemble.joblib") -> None:
        artifact = joblib.load(model_path)
        self.artifact_type = artifact.get("type", "tfidf_ensemble") if isinstance(artifact, dict) else "unknown"
        self.metadata = artifact.get("metadata", {}) if isinstance(artifact, dict) else {}
        self.dedicated_model = None

        if isinstance(artifact, dict) and "model" in artifact:
            # Format generated by train_dedicated_local.py.
            self.dedicated_model = artifact["model"]
            self.models = dict(getattr(self.dedicated_model, "fitted_estimators_", []))
            self.weights = dict(getattr(self.dedicated_model, "weights", {}))
            self.threshold = float(
                getattr(self.dedicated_model, "threshold", self.metadata.get("threshold", 0.5))
            )
        elif isinstance(artifact, dict) and "models" in artifact:
            # Original retained AIrumer ensemble artifact.
            self.models = artifact["models"]
            self.weights = artifact.get("weights", {name: 1.0 for name in self.models})
            self.threshold = float(artifact.get("threshold", self.metadata.get("threshold", 0.5)))
        else:
            raise ValueError(
                f"Unsupported model artifact format in {model_path}. "
                "Expected a dict with either key 'models' or key 'model'."
            )

    def predict_proba(self, text: str) -> np.ndarray:
        processed = preprocess_text(text)

        if self.dedicated_model is not None:
            return np.asarray(self.dedicated_model.predict_proba([processed])[0], dtype=float)

        probs = []
        weights = []
        for name, model in self.models.items():
            probs.append(model.predict_proba([processed])[0])
            weights.append(float(self.weights.get(name, 1.0)))
        weight_arr = np.asarray(weights, dtype=float)
        weight_arr = weight_arr / weight_arr.sum()
        return np.tensordot(weight_arr, np.stack(probs, axis=0), axes=(0, 0))

    def classify(self, text: str) -> int:
        probs = self.predict_proba(text)
        return int(probs[1] >= self.threshold)

    def _select_explainable_linear_model(self):
        # Known names in the retained AIrumer artifact and in dedicated_local.joblib.
        preferred = [
            "word_lr",
            "lr_union_c8",
            "multi_lr_c8.0",
            "multi_lr_c4.0",
            "multi_lr_c12.0",
            "multi_lr_c20.0",
            "multi_lr_c2.0",
        ]
        for key in preferred:
            if key in self.models:
                return self.models[key]
        for _, model in self.models.items():
            try:
                clf = model.named_steps.get("clf")
                if hasattr(clf, "coef_"):
                    return model
            except Exception:
                continue
        return None

    def _extract_lr_feature_cues(self, text: str, label: int, k: int = 8) -> List[str]:
        """Extract readable cues from a linear TF-IDF component when available."""
        model = self._select_explainable_linear_model()
        if model is None or not hasattr(model, "named_steps"):
            return []
        clf = model.named_steps.get("clf")
        features = model.named_steps.get("features")
        if features is None or clf is None or not hasattr(clf, "coef_"):
            return []

        x = features.transform([preprocess_text(text)])
        if x.nnz == 0:
            return []
        feature_names = np.asarray(features.get_feature_names_out())
        coef = clf.coef_[0]
        signed = x.data * coef[x.indices]
        target_scores = signed if label == 1 else -signed
        order = np.argsort(target_scores)[::-1]

        cues: List[str] = []
        seen = set()
        for pos in order:
            if target_scores[pos] <= 0:
                continue
            feat = str(feature_names[x.indices[pos]])
            if feat in seen:
                continue
            seen.add(feat)
            cues.append(feat)
            if len(cues) >= k:
                break
        return cues

    def explain(self, text: str) -> str:
        label = self.classify(text)
        probs = self.predict_proba(text)
        confidence = float(probs[label])
        cues = self._extract_lr_feature_cues(text, label)
        if cues:
            cue_text = "、".join([f"“{cue}”" for cue in cues])
            basis = f"主要证据包括 {cue_text} 等词或短语，这些特征在本地集成模型中更支持“{LABEL_NAMES[label]}”。"
        else:
            basis = "文本中没有明显的单个高权重词，模型主要依据整体 word/char TF-IDF 表示进行判断。"
        return (
            f"本地集成模型判断为{LABEL_NAMES[label]}（类别 {label}），置信度约为 {confidence:.3f}。"
            f"{basis} 本地模型由词级/字符级 TF-IDF 与多个线性分类器加权融合得到。"
        )

    def feature_cues(self, text: str, label: int, k: int = 8) -> List[str]:
        return self._extract_lr_feature_cues(text, label, k=k)

    def predict_with_reason(self, text: str) -> Dict[str, object]:
        label = self.classify(text)
        probs = self.predict_proba(text)
        return {
            "label": label,
            "label_name": LABEL_NAMES[label],
            "prob_non_rumor": float(probs[0]),
            "prob_rumor": float(probs[1]),
            "confidence": float(probs[label]),
            "reason": self.explain(text),
            "source": "local_ensemble",
        }


class HybridRumourDetectClass:
    """High-accuracy hybrid detector with optional LLM review for hard samples."""

    def __init__(
        self,
        model_path: str | Path = "models/ensemble.joblib",
        retriever_path: str | Path = "models/retriever.joblib",
        config_path: str | Path = "config.json",
        use_llm: bool = False,
    ) -> None:
        self.local = EnsembleRumourDetectClass(model_path)
        self.config = load_config(config_path)
        hybrid_cfg = self.config.get("hybrid", {})
        self.high_threshold = float(hybrid_cfg.get("high_confidence_threshold", 0.85))
        self.low_threshold = float(hybrid_cfg.get("low_confidence_threshold", 0.65))
        self.top_k_examples = int(hybrid_cfg.get("top_k_examples", 5))
        self.use_llm = use_llm
        self.config_path = config_path
        self.retriever = None
        self.reranker = None
        if use_llm:
            self.retriever = SimilarExampleRetriever(retriever_path)
            self.reranker = LLMReranker(config_path=config_path)

    def _needs_llm(self, confidence: float) -> bool:
        return self.use_llm and confidence < self.high_threshold

    def classify(self, text: str) -> int:
        return int(self.predict_with_reason(text)["label"])

    def explain(self, text: str) -> str:
        return str(self.predict_with_reason(text)["reason"])

    def predict_proba(self, text: str) -> np.ndarray:
        return self.local.predict_proba(text)

    def predict_with_reason(self, text: str) -> Dict[str, object]:
        local_result = self.local.predict_with_reason(text)
        local_label = int(local_result["label"])
        confidence = float(local_result["confidence"])
        cues = self.local.feature_cues(text, local_label)

        if not self._needs_llm(confidence):
            local_result["llm_used"] = False
            return local_result

        if self.retriever is None or self.reranker is None:
            local_result["llm_used"] = False
            local_result["reason"] += " 由于检索器或大模型复核器未初始化，未调用大模型。"
            return local_result

        similar_examples = self.retriever.retrieve(text, k=self.top_k_examples)
        llm_review = self.reranker.review(text, local_label, confidence, cues, similar_examples)
        llm_label = int(llm_review["label"])

        probs = self.local.predict_proba(text)
        final_label = local_label
        source = "local_ensemble"
        if confidence < self.low_threshold:
            final_label = llm_label
            source = "deepseek_reasoner_review"
        elif llm_label == local_label:
            final_label = local_label
            source = "local_ensemble_confirmed_by_deepseek"
        else:
            final_label = local_label
            source = "local_ensemble_llm_disagreed"

        final_reason = (
            f"本地集成模型预测为{LABEL_NAMES[local_label]}（类别 {local_label}），置信度 {confidence:.3f}。"
            f"大模型 DeepSeek V3.2 思考模式复核结论为{LABEL_NAMES[llm_label]}（类别 {llm_label}）。"
            f"最终采用{LABEL_NAMES[final_label]}（类别 {final_label}）。"
            f"本地重要特征：{('、'.join(cues) if cues else '无明显高权重特征')}。"
            f"大模型解释：{llm_review['reason']}"
        )
        return {
            "label": final_label,
            "label_name": LABEL_NAMES[final_label],
            "prob_non_rumor": float(probs[0]),
            "prob_rumor": float(probs[1]),
            "confidence": float(probs[final_label]) if final_label == local_label else float(probs[llm_label]),
            "local_label": local_label,
            "llm_label": llm_label,
            "llm_used": True,
            "source": source,
            "similar_examples": similar_examples,
            "reason": final_reason,
        }


RumourDetectClass = HybridRumourDetectClass
